"""
Report generator for AI Repo Scout.
Creates beautiful markdown, HTML, and JSON reports for GitHub Pages deployment.
"""

import os
import json
from datetime import datetime, timedelta
from typing import Dict, List, Optional
import pandas as pd
import logging
from jinja2 import Template

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


class ReportGenerator:
    """Generates various report formats for repository analysis."""
    
    def __init__(self, config: Dict = None):
        """Initialize report generator.
        
        Args:
            config: Configuration dictionary for output settings
        """
        self.config = config or {}
        self.reports_dir = self.config.get('reports_dir', 'reports')
        self.formats = self.config.get('formats', ['markdown', 'json'])
        
        # Create reports directory
        os.makedirs(self.reports_dir, exist_ok=True)
        
        # Templates for different report types
        self.templates = self._load_templates()
    
    def _load_templates(self) -> Dict[str, Template]:
        """Load Jinja2 templates for report generation."""
        
        # Markdown report template
        markdown_template = Template("""
# 🚀 AI Repo Scout Report
## {{ timeframe.title() }} Trending Repositories

**Generated on:** {{ timestamp }}  
**Total Repositories Analyzed:** {{ total_repos }}  
**Average Momentum Score:** {{ avg_momentum_score | round(2) }}

---

## 📊 Executive Summary

{{ summary_text }}

### 🎯 Key Recommendations
{% for recommendation in recommendations %}
- {{ recommendation }}
{% endfor %}

---

## 🔥 Top Trending Repositories

{% for repo in top_repos %}
### {{ loop.index }}. [{{ repo.name }}]({{ repo.html_url }})

**{{ repo.full_name }}** {% if repo.language %}({{ repo.language }}){% endif %}

{{ repo.description or "No description available" }}

**Metrics:**
- ⭐ **Stars:** {{ "{:,}".format(repo.stars) }}
- 🍴 **Forks:** {{ "{:,}".format(repo.forks) }}
- 🏃 **Momentum Score:** {{ repo.momentum_score | round(1) }}/100
- 📈 **Star Velocity:** {{ repo.star_velocity | round(2) }} stars/day
- 👥 **Contributors:** {{ repo.contributors }}
{% if repo.topics %}
- 🏷️ **Topics:** {{ repo.topics | join(', ') }}
{% endif %}

{% if repo.ai_summary %}
**AI Summary:** {{ repo.ai_summary }}
{% endif %}

---
{% endfor %}

## 📈 Trending Analysis

### Language Distribution
{% for language, count in language_stats.items() %}
- **{{ language }}**: {{ count }} repositories
{% endfor %}

### Repository Types
{% for repo_type, count in repo_types.items() %}
- **{{ repo_type.title() }}**: {{ count }} repositories
{% endfor %}

### Growth Patterns
{% for pattern, data in growth_patterns.items() %}
#### {{ pattern.replace('_', ' ').title() }}
{% for key, value in data.items() %}
- **{{ key }}**: {{ value | round(2) if value is number else value }}
{% endfor %}
{% endfor %}

---

## 🤖 AI-Powered Insights

### Top Trending Topics
{% for topic, count in trending_topics.items() %}
- **{{ topic }}**: {{ count }} repositories
{% endfor %}

### Category Breakdown
{% for category, repos in categories.items() %}
- **{{ category }}**: {{ repos | length }} repositories
{% endfor %}

---

## 📊 Detailed Metrics

| Repository | Language | Stars | Momentum | Growth Potential | Type |
|------------|----------|-------|----------|------------------|------|
{% for repo in detailed_repos %}
| [{{ repo.name }}]({{ repo.html_url }}) | {{ repo.language or "N/A" }} | {{ "{:,}".format(repo.stars) }} | {{ repo.momentum_score | round(1) }} | {{ repo.growth_potential | round(1) if repo.growth_potential else "N/A" }} | {{ repo.repo_type or "N/A" }} |
{% endfor %}

---

## 📅 Historical Context

This report covers {{ timeframe }} trending repositories from GitHub. Data collection and analysis performed using:

- **GitHub REST API** for repository data
- **Hugging Face Transformers** for AI-powered summaries
- **Custom momentum scoring** algorithm
- **Zero-cost infrastructure** (all free tools)

### Methodology

1. **Data Collection**: Fetch trending repositories using GitHub API
2. **Quality Filtering**: Apply minimum thresholds for stars, activity, and completeness
3. **AI Analysis**: Generate summaries and insights using open-source models
4. **Momentum Scoring**: Calculate composite scores based on growth velocity, engagement, and quality
5. **Trend Analysis**: Identify patterns and generate recommendations

---

*Report generated by [AI Repo Scout](https://github.com/superdividenz/AI-Repo-Scout) - Zero-cost AI-powered repository discovery*
""")

        # HTML report template
        html_template = Template("""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>🚀 AI Repo Scout - {{ timeframe.title() }} Report</title>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; margin: 0; padding: 20px; background: #f5f7fa; }
        .container { max-width: 1200px; margin: 0 auto; background: white; padding: 30px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
        h1 { color: #2c3e50; border-bottom: 3px solid #3498db; padding-bottom: 10px; }
        h2 { color: #34495e; margin-top: 30px; }
        .repo-card { border: 1px solid #e1e8ed; border-radius: 8px; padding: 20px; margin: 15px 0; background: #fafbfc; }
        .repo-title { font-size: 1.4em; margin-bottom: 10px; }
        .repo-title a { color: #0366d6; text-decoration: none; }
        .repo-title a:hover { text-decoration: underline; }
        .metrics { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 15px; margin: 15px 0; }
        .metric { background: white; padding: 10px; border-radius: 5px; border-left: 4px solid #3498db; }
        .metric-label { font-weight: bold; color: #7f8c8d; font-size: 0.9em; }
        .metric-value { font-size: 1.2em; color: #2c3e50; }
        .topics { margin: 10px 0; }
        .topic { background: #e3f2fd; color: #1976d2; padding: 4px 8px; border-radius: 12px; font-size: 0.8em; margin: 2px; display: inline-block; }
        .summary-stats { display: grid; grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); gap: 20px; margin: 20px 0; }
        .stat-card { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 20px; border-radius: 10px; text-align: center; }
        .stat-number { font-size: 2em; font-weight: bold; }
        .stat-label { opacity: 0.9; }
        .recommendations { background: #f8f9fa; border-left: 4px solid #28a745; padding: 15px; margin: 20px 0; }
        .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #e1e8ed; color: #7f8c8d; text-align: center; }
    </style>
</head>
<body>
    <div class="container">
        <h1>🚀 AI Repo Scout Report</h1>
        <p><strong>{{ timeframe.title() }} Trending Repositories</strong> | Generated on {{ timestamp }}</p>
        
        <div class="summary-stats">
            <div class="stat-card">
                <div class="stat-number">{{ total_repos }}</div>
                <div class="stat-label">Repositories Analyzed</div>
            </div>
            <div class="stat-card">
                <div class="stat-number">{{ avg_momentum_score | round(1) }}</div>
                <div class="stat-label">Avg Momentum Score</div>
            </div>
            <div class="stat-card">
                <div class="stat-number">{{ language_stats | length }}</div>
                <div class="stat-label">Programming Languages</div>
            </div>
        </div>

        {% if recommendations %}
        <div class="recommendations">
            <h3>🎯 Key Recommendations</h3>
            <ul>
            {% for recommendation in recommendations %}
                <li>{{ recommendation }}</li>
            {% endfor %}
            </ul>
        </div>
        {% endif %}

        <h2>🔥 Top Trending Repositories</h2>
        
        {% for repo in top_repos %}
        <div class="repo-card">
            <div class="repo-title">
                {{ loop.index }}. <a href="{{ repo.html_url }}" target="_blank">{{ repo.name }}</a>
                {% if repo.language %}<span style="color: #7f8c8d;">({{ repo.language }})</span>{% endif %}
            </div>
            <p><strong>{{ repo.full_name }}</strong></p>
            <p>{{ repo.description or "No description available" }}</p>
            
            <div class="metrics">
                <div class="metric">
                    <div class="metric-label">⭐ Stars</div>
                    <div class="metric-value">{{ "{:,}".format(repo.stars) }}</div>
                </div>
                <div class="metric">
                    <div class="metric-label">🍴 Forks</div>
                    <div class="metric-value">{{ "{:,}".format(repo.forks) }}</div>
                </div>
                <div class="metric">
                    <div class="metric-label">🏃 Momentum Score</div>
                    <div class="metric-value">{{ repo.momentum_score | round(1) }}/100</div>
                </div>
                <div class="metric">
                    <div class="metric-label">📈 Star Velocity</div>
                    <div class="metric-value">{{ repo.star_velocity | round(2) }}/day</div>
                </div>
            </div>

            {% if repo.topics %}
            <div class="topics">
                {% for topic in repo.topics %}
                <span class="topic">{{ topic }}</span>
                {% endfor %}
            </div>
            {% endif %}

            {% if repo.ai_summary %}
            <p><strong>AI Summary:</strong> {{ repo.ai_summary }}</p>
            {% endif %}
        </div>
        {% endfor %}

        <div class="footer">
            <p>Report generated by <a href="https://github.com/superdividenz/AI-Repo-Scout">AI Repo Scout</a> - Zero-cost AI-powered repository discovery</p>
        </div>
    </div>
</body>
</html>
""")

        return {
            'markdown': markdown_template,
            'html': html_template
        }
    
    def generate_markdown_report(self, df: pd.DataFrame, insights: Dict, timeframe: str) -> str:
        """Generate a comprehensive markdown report."""
        
        # Prepare data for template
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S UTC")
        
        # Get top repositories
        top_repos = df.head(20).to_dict('records') if not df.empty else []
        
        # Add AI summaries if available
        ai_summaries = insights.get('ai_summaries', {})
        for repo in top_repos:
            repo['ai_summary'] = ai_summaries.get(repo.get('full_name', ''), '')
        
        # Prepare template data
        template_data = {
            'timeframe': timeframe,
            'timestamp': timestamp,
            'total_repos': len(df) if not df.empty else 0,
            'avg_momentum_score': df['momentum_score'].mean() if not df.empty and 'momentum_score' in df.columns else 0,
            'top_repos': top_repos,
            'detailed_repos': df.head(50).to_dict('records') if not df.empty else [],
            'recommendations': insights.get('recommendations', []),
            'language_stats': insights.get('language_trends', {}),
            'repo_types': insights.get('repository_types', {}),
            'growth_patterns': insights.get('growth_patterns', {}),
            'trending_topics': insights.get('ai_analysis', {}).get('trending_topics', {}),
            'categories': insights.get('ai_analysis', {}).get('categories', {}),
            'summary_text': self._generate_summary_text(insights)
        }
        
        # Render template
        report = self.templates['markdown'].render(**template_data)
        
        # Save to file
        filename = f"{timeframe}_report_{datetime.now().strftime('%Y%m%d')}.md"
        filepath = os.path.join(self.reports_dir, filename)
        
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(report)
        
        logger.info(f"Markdown report generated: {filepath}")
        return filepath
    
    def generate_html_report(self, df: pd.DataFrame, insights: Dict, timeframe: str) -> str:
        """Generate an HTML report for web viewing."""
        
        # Prepare data (similar to markdown)
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S UTC")
        top_repos = df.head(15).to_dict('records') if not df.empty else []
        
        # Add AI summaries
        ai_summaries = insights.get('ai_summaries', {})
        for repo in top_repos:
            repo['ai_summary'] = ai_summaries.get(repo.get('full_name', ''), '')
        
        template_data = {
            'timeframe': timeframe,
            'timestamp': timestamp,
            'total_repos': len(df) if not df.empty else 0,
            'avg_momentum_score': df['momentum_score'].mean() if not df.empty and 'momentum_score' in df.columns else 0,
            'top_repos': top_repos,
            'recommendations': insights.get('recommendations', []),
            'language_stats': insights.get('language_trends', {})
        }
        
        # Render template
        report = self.templates['html'].render(**template_data)
        
        # Save to file
        filename = f"{timeframe}_report_{datetime.now().strftime('%Y%m%d')}.html"
        filepath = os.path.join(self.reports_dir, filename)
        
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(report)
        
        logger.info(f"HTML report generated: {filepath}")
        return filepath
    
    def generate_json_report(self, df: pd.DataFrame, insights: Dict, timeframe: str) -> str:
        """Generate a JSON report for API consumption."""
        
        # Convert DataFrame to records
        repositories = df.to_dict('records') if not df.empty else []
        
        # Prepare JSON structure
        report_data = {
            'metadata': {
                'generated_at': datetime.now().isoformat(),
                'timeframe': timeframe,
                'total_repositories': len(repositories),
                'report_version': '1.0',
                'generator': 'AI Repo Scout'
            },
            'summary': {
                'total_repos': len(repositories),
                'avg_momentum_score': df['momentum_score'].mean() if not df.empty and 'momentum_score' in df.columns else 0,
                'top_momentum_score': df['momentum_score'].max() if not df.empty and 'momentum_score' in df.columns else 0,
                'languages_covered': list(insights.get('language_trends', {}).keys()),
                'repository_types': insights.get('repository_types', {})
            },
            'repositories': repositories,
            'insights': insights,
            'recommendations': insights.get('recommendations', [])
        }
        
        # Save to file
        filename = f"{timeframe}_report_{datetime.now().strftime('%Y%m%d')}.json"
        filepath = os.path.join(self.reports_dir, filename)
        
        with open(filepath, 'w', encoding='utf-8') as f:
            json.dump(report_data, f, indent=2, default=str)
        
        logger.info(f"JSON report generated: {filepath}")
        return filepath
    
    def generate_github_pages_index(self, recent_reports: List[str]) -> str:
        """Generate an index.html file for GitHub Pages."""
        
        index_template = Template("""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>🚀 AI Repo Scout - Trending Repository Reports</title>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; margin: 0; padding: 20px; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); min-height: 100vh; }
        .container { max-width: 1000px; margin: 0 auto; background: white; padding: 40px; border-radius: 15px; box-shadow: 0 10px 30px rgba(0,0,0,0.2); }
        h1 { text-align: center; color: #2c3e50; margin-bottom: 10px; font-size: 2.5em; }
        .subtitle { text-align: center; color: #7f8c8d; margin-bottom: 40px; font-size: 1.2em; }
        .reports-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: 20px; margin: 30px 0; }
        .report-card { border: 1px solid #e1e8ed; border-radius: 10px; padding: 20px; background: #fafbfc; transition: transform 0.2s, box-shadow 0.2s; }
        .report-card:hover { transform: translateY(-5px); box-shadow: 0 5px 20px rgba(0,0,0,0.1); }
        .report-title { font-size: 1.3em; margin-bottom: 10px; color: #2c3e50; }
        .report-date { color: #7f8c8d; font-size: 0.9em; margin-bottom: 15px; }
        .report-links a { display: inline-block; margin: 5px 10px 5px 0; padding: 8px 16px; background: #3498db; color: white; text-decoration: none; border-radius: 5px; font-size: 0.9em; }
        .report-links a:hover { background: #2980b9; }
        .features { background: #f8f9fa; padding: 25px; border-radius: 10px; margin: 30px 0; }
        .features h3 { color: #2c3e50; margin-bottom: 15px; }
        .features ul { list-style: none; padding: 0; }
        .features li { padding: 5px 0; color: #34495e; }
        .features li:before { content: "✨ "; color: #3498db; }
        .footer { text-align: center; margin-top: 40px; padding-top: 20px; border-top: 1px solid #e1e8ed; color: #7f8c8d; }
    </style>
</head>
<body>
    <div class="container">
        <h1>🚀 AI Repo Scout</h1>
        <p class="subtitle">Discover trending GitHub repositories with AI-powered insights</p>
        
        <div class="features">
            <h3>📊 What's Inside Our Reports</h3>
            <ul>
                <li><strong>AI-Powered Analysis</strong> - Automatic repository summaries using Hugging Face models</li>
                <li><strong>Momentum Scoring</strong> - Custom algorithm to identify rapidly growing projects</li>
                <li><strong>Trend Analysis</strong> - Language trends, growth patterns, and community insights</li>
                <li><strong>Zero-Cost Infrastructure</strong> - Built entirely with free APIs and open-source tools</li>
                <li><strong>Daily Updates</strong> - Fresh data and insights updated automatically</li>
            </ul>
        </div>

        <h2>📄 Latest Reports</h2>
        <div class="reports-grid">
            {% for report in reports %}
            <div class="report-card">
                <div class="report-title">{{ report.title }}</div>
                <div class="report-date">{{ report.date }}</div>
                <div class="report-links">
                    {% if report.markdown %}<a href="{{ report.markdown }}">📝 Markdown</a>{% endif %}
                    {% if report.html %}<a href="{{ report.html }}">🌐 HTML</a>{% endif %}
                    {% if report.json %}<a href="{{ report.json }}">📊 JSON</a>{% endif %}
                </div>
            </div>
            {% endfor %}
        </div>

        <div class="footer">
            <p>Generated by <a href="https://github.com/superdividenz/AI-Repo-Scout">AI Repo Scout</a></p>
            <p>Last updated: {{ last_updated }}</p>
        </div>
    </div>
</body>
</html>
""")
        
        # Process recent reports
        reports = []
        for report_path in recent_reports[-10:]:  # Show last 10 reports
            filename = os.path.basename(report_path)
            if filename.endswith('.md'):
                timeframe = filename.split('_')[0]
                date = filename.split('_')[-1].replace('.md', '')
                
                # Format date
                try:
                    date_obj = datetime.strptime(date, '%Y%m%d')
                    formatted_date = date_obj.strftime('%B %d, %Y')
                except:
                    formatted_date = date
                
                reports.append({
                    'title': f"{timeframe.title()} Trending Report",
                    'date': formatted_date,
                    'markdown': filename,
                    'html': filename.replace('.md', '.html'),
                    'json': filename.replace('.md', '.json')
                })
        
        # Render index page
        index_content = index_template.render(
            reports=reports,
            last_updated=datetime.now().strftime('%Y-%m-%d %H:%M:%S UTC')
        )
        
        # Save index.html
        index_path = os.path.join(self.reports_dir, 'index.html')
        with open(index_path, 'w', encoding='utf-8') as f:
            f.write(index_content)
        
        logger.info(f"GitHub Pages index generated: {index_path}")
        return index_path
    
    def _generate_summary_text(self, insights: Dict) -> str:
        """Generate a summary text based on insights."""
        summary_parts = []
        
        if insights.get('summary', {}).get('total_repos', 0) > 0:
            total = insights['summary']['total_repos']
            avg_momentum = insights['summary'].get('avg_momentum_score', 0)
            
            summary_parts.append(f"Analyzed {total} trending repositories with an average momentum score of {avg_momentum:.1f}/100.")
        
        if insights.get('language_trends'):
            top_lang = list(insights['language_trends'].keys())[0]
            summary_parts.append(f"{top_lang} repositories are currently showing the highest momentum.")
        
        if insights.get('recommendations'):
            rec_count = len(insights['recommendations'])
            summary_parts.append(f"Generated {rec_count} actionable recommendations for developers and investors.")
        
        return " ".join(summary_parts) if summary_parts else "Comprehensive analysis of trending GitHub repositories using AI-powered insights."
    
    def generate_all_reports(self, df: pd.DataFrame, insights: Dict, timeframe: str) -> List[str]:
        """Generate all configured report formats."""
        
        report_files = []
        
        if 'markdown' in self.formats:
            md_path = self.generate_markdown_report(df, insights, timeframe)
            report_files.append(md_path)
        
        if 'html' in self.formats:
            html_path = self.generate_html_report(df, insights, timeframe)
            report_files.append(html_path)
        
        if 'json' in self.formats:
            json_path = self.generate_json_report(df, insights, timeframe)
            report_files.append(json_path)
        
        # Generate GitHub Pages index
        try:
            index_path = self.generate_github_pages_index(report_files)
            report_files.append(index_path)
        except Exception as e:
            logger.error(f"Failed to generate GitHub Pages index: {e}")
        
        return report_files
    
    def cleanup_old_reports(self, days_to_keep: int = 30):
        """Clean up old report files."""
        
        cutoff_date = datetime.now() - timedelta(days=days_to_keep)
        cleaned_count = 0
        
        for filename in os.listdir(self.reports_dir):
            if filename.startswith(('daily_', 'weekly_', 'monthly_')) and not filename.endswith('index.html'):
                filepath = os.path.join(self.reports_dir, filename)
                
                try:
                    file_date = os.path.getctime(filepath)
                    if datetime.fromtimestamp(file_date) < cutoff_date:
                        os.remove(filepath)
                        cleaned_count += 1
                except Exception as e:
                    logger.error(f"Failed to clean up {filename}: {e}")
        
        if cleaned_count > 0:
            logger.info(f"Cleaned up {cleaned_count} old report files")
        
        return cleaned_count